sudo: required
branches:
  only:
  - main
  - staging
  - live
language: java
jdk:
  - openjdk8
jobs:
  include:
    - stage: test
      script: ./infrastructure/ci-angular-user-site-test.sh
      addons:
        chrome: stable
    - stage: test
      script: ./infrastructure/ci-java-user-site-test.sh
    - stage: test
      script: ./infrastructure/ci-admin-site-test.sh
    - stage: deploy-to-int
      if: branch=main
      script: SPACE=int ./infrastructure/deploy.sh
    - stage: deploy-to-staging
      if: branch=staging
      script: SPACE=staging ./infrastructure/deploy.sh
    - stage: deploy-to-live
      if: branch=live
      script: SPACE=live ./infrastructure/deploy.sh
    - stage: integration-tests
      script: ./infrastructure/ci-integration-tests.sh
      addons:
        chrome: stable
notifications:
  email:
    - Team-BEISESASSupport@softwire.com
